// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod wasi {
  pub mod frame_buffer {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod frame_buffer {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type Context = super::super::super::wasi::graphics_context::graphics_context::Context;
      pub type AbstractBuffer = super::super::super::wasi::graphics_context::graphics_context::AbstractBuffer;

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Device{
        handle: _rt::Resource<Device>,
      }

      impl Device{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Device{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:frame-buffer/frame-buffer@0.0.1")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]device"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Buffer{
        handle: _rt::Resource<Buffer>,
      }

      impl Buffer{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Buffer{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:frame-buffer/frame-buffer@0.0.1")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]buffer"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      impl Device {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn new() -> Self{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:frame-buffer/frame-buffer@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[constructor]device"]
              fn wit_import0() -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0() -> i32 { unreachable!() }
            let ret = wit_import0();
            Device::from_handle(ret as u32)
          }
        }
      }
      impl Device {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn connect_graphics_context(&self,context: &Context,) -> (){
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:frame-buffer/frame-buffer@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[method]device.connect-graphics-context"]
              fn wit_import0(_: i32, _: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, _: i32, ) { unreachable!() }
            wit_import0((self).handle() as i32, (context).handle() as i32);
          }
        }
      }
      impl Buffer {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn from_graphics_buffer(buffer: AbstractBuffer,) -> Buffer{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:frame-buffer/frame-buffer@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[static]buffer.from-graphics-buffer"]
              fn wit_import0(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) -> i32 { unreachable!() }
            let ret = wit_import0((&buffer).take_handle() as i32);
            Buffer::from_handle(ret as u32)
          }
        }
      }
      impl Buffer {
        #[allow(unused_unsafe, clippy::all)]
        /// TODO: This should be replcated with something that doesn't require a copy.
        #[allow(async_fn_in_trait)]
        pub fn get(&self,) -> _rt::Vec::<u8>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:frame-buffer/frame-buffer@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[method]buffer.get"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = *ptr0.add(0).cast::<*mut u8>();
            let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len4 = l3;
            let result5 = <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l2.cast(), len4, len4));
            result5
          }
        }
      }
      impl Buffer {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn set(&self,val: &[u8],) -> (){
          unsafe {
            let vec0 = val;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:frame-buffer/frame-buffer@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[method]buffer.set"]
              fn wit_import1(_: i32, _: *mut u8, _: usize, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, _: usize, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0.cast_mut(), len0);
          }
        }
      }

    }

  }
  pub mod graphics_context {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod graphics_context {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Context{
        handle: _rt::Resource<Context>,
      }

      impl Context{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Context{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:graphics-context/graphics-context@0.0.1")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]context"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct AbstractBuffer{
        handle: _rt::Resource<AbstractBuffer>,
      }

      impl AbstractBuffer{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for AbstractBuffer{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:graphics-context/graphics-context@0.0.1")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]abstract-buffer"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      impl Context {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn new() -> Self{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:graphics-context/graphics-context@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[constructor]context"]
              fn wit_import0() -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0() -> i32 { unreachable!() }
            let ret = wit_import0();
            Context::from_handle(ret as u32)
          }
        }
      }
      impl Context {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn get_current_buffer(&self,) -> AbstractBuffer{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:graphics-context/graphics-context@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[method]context.get-current-buffer"]
              fn wit_import0(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) -> i32 { unreachable!() }
            let ret = wit_import0((self).handle() as i32);
            AbstractBuffer::from_handle(ret as u32)
          }
        }
      }
      impl Context {
        #[allow(unused_unsafe, clippy::all)]
        /// TODO: might want to remove this.
        #[allow(async_fn_in_trait)]
        pub fn present(&self,) -> (){
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:graphics-context/graphics-context@0.0.1")]
            unsafe extern "C" {
              #[link_name = "[method]context.present"]
              fn wit_import0(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) { unreachable!() }
            wit_import0((self).handle() as i32);
          }
        }
      }

    }

  }
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != 0 && handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub use alloc_crate::vec::Vec;
  extern crate alloc as alloc_crate;
}

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.51.0:wasi:frame-buffer@0.0.1:imports:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 762] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xfc\x04\x01A\x02\x01\
A\x06\x01B\x0b\x04\0\x07context\x03\x01\x04\0\x0fabstract-buffer\x03\x01\x01i\0\x01\
@\0\0\x02\x04\0\x14[constructor]context\x01\x03\x01h\0\x01i\x01\x01@\x01\x04self\
\x04\0\x05\x04\0\"[method]context.get-current-buffer\x01\x06\x01@\x01\x04self\x04\
\x01\0\x04\0\x17[method]context.present\x01\x07\x03\0,wasi:graphics-context/grap\
hics-context@0.0.1\x05\0\x02\x03\0\0\x07context\x02\x03\0\0\x0fabstract-buffer\x01\
B\x17\x02\x03\x02\x01\x01\x04\0\x07context\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0f\
abstract-buffer\x03\0\x02\x04\0\x06device\x03\x01\x04\0\x06buffer\x03\x01\x01i\x04\
\x01@\0\0\x06\x04\0\x13[constructor]device\x01\x07\x01h\x04\x01h\x01\x01@\x02\x04\
self\x08\x07context\x09\x01\0\x04\0'[method]device.connect-graphics-context\x01\x0a\
\x01i\x03\x01i\x05\x01@\x01\x06buffer\x0b\0\x0c\x04\0#[static]buffer.from-graphi\
cs-buffer\x01\x0d\x01h\x05\x01p}\x01@\x01\x04self\x0e\0\x0f\x04\0\x12[method]buf\
fer.get\x01\x10\x01@\x02\x04self\x0e\x03val\x0f\x01\0\x04\0\x12[method]buffer.se\
t\x01\x11\x03\0$wasi:frame-buffer/frame-buffer@0.0.1\x05\x03\x04\0\x1fwasi:frame\
-buffer/imports@0.0.1\x04\0\x0b\x0d\x01\0\x07imports\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.244.0\x10wit-bindgen-rust\x060.51.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

